[2021-03-04 22:52:45,908] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: clean_data.merge_data 2021-03-04T22:51:08.529824+00:00 [queued]>
[2021-03-04 22:52:45,943] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: clean_data.merge_data 2021-03-04T22:51:08.529824+00:00 [queued]>
[2021-03-04 22:52:45,944] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2021-03-04 22:52:45,944] {taskinstance.py:881} INFO - Starting attempt 1 of 2
[2021-03-04 22:52:45,944] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2021-03-04 22:52:45,975] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): merge_data> on 2021-03-04T22:51:08.529824+00:00
[2021-03-04 22:52:45,978] {standard_task_runner.py:54} INFO - Started process 555 to run task
[2021-03-04 22:52:46,005] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'clean_data', 'merge_data', '2021-03-04T22:51:08.529824+00:00', '--job_id', '41', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/data_clean.py', '--cfg_path', '/tmp/tmppem0qf53']
[2021-03-04 22:52:46,007] {standard_task_runner.py:78} INFO - Job 41: Subtask merge_data
[2021-03-04 22:52:46,062] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: clean_data.merge_data 2021-03-04T22:51:08.529824+00:00 [running]> 6623e80cd770
[2021-03-04 22:52:46,289] {python_operator.py:114} INFO - Done. Returned value was: None
[2021-03-04 22:52:46,300] {taskinstance.py:1070} INFO - Marking task as SUCCESS.dag_id=clean_data, task_id=merge_data, execution_date=20210304T225108, start_date=20210304T225245, end_date=20210304T225246
[2021-03-04 22:52:50,887] {local_task_job.py:102} INFO - Task exited with return code 0
