[2021-03-04 20:09:52,673] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: clean_data.clean_data_search_request 2021-03-04T20:04:18.948253+00:00 [queued]>
[2021-03-04 20:09:52,713] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: clean_data.clean_data_search_request 2021-03-04T20:04:18.948253+00:00 [queued]>
[2021-03-04 20:09:52,714] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2021-03-04 20:09:52,714] {taskinstance.py:881} INFO - Starting attempt 2 of 2
[2021-03-04 20:09:52,714] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2021-03-04 20:09:52,744] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): clean_data_search_request> on 2021-03-04T20:04:18.948253+00:00
[2021-03-04 20:09:52,747] {standard_task_runner.py:54} INFO - Started process 4340 to run task
[2021-03-04 20:09:52,785] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'clean_data', 'clean_data_search_request', '2021-03-04T20:04:18.948253+00:00', '--job_id', '32', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/data_clean.py', '--cfg_path', '/tmp/tmpmdgxgqtv']
[2021-03-04 20:09:52,788] {standard_task_runner.py:78} INFO - Job 32: Subtask clean_data_search_request
[2021-03-04 20:09:52,840] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: clean_data.clean_data_search_request 2021-03-04T20:04:18.948253+00:00 [running]> 6623e80cd770
[2021-03-04 20:09:52,900] {logging_mixin.py:112} WARNING - /opt/airflow/dags/data_clean.py:120: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ts'][count] = cleaned
[2021-03-04 20:09:52,900] {taskinstance.py:1150} ERROR - name 'search_request' is not defined
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_clean.py", line 121, in clean_data_df
    df['ts'] = pd.to_datetime(search_request['ts'], utc=True)
NameError: name 'search_request' is not defined
[2021-03-04 20:09:52,902] {taskinstance.py:1194} INFO - Marking task as FAILED. dag_id=clean_data, task_id=clean_data_search_request, execution_date=20210304T200418, start_date=20210304T200952, end_date=20210304T200952
[2021-03-04 20:09:57,658] {local_task_job.py:102} INFO - Task exited with return code 1
[2021-03-04 22:33:31,194] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: clean_data.clean_data_search_request 2021-03-04T20:04:18.948253+00:00 [queued]>
[2021-03-04 22:33:31,232] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: clean_data.clean_data_search_request 2021-03-04T20:04:18.948253+00:00 [queued]>
[2021-03-04 22:33:31,233] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2021-03-04 22:33:31,233] {taskinstance.py:881} INFO - Starting attempt 2 of 2
[2021-03-04 22:33:31,234] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2021-03-04 22:33:31,260] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): clean_data_search_request> on 2021-03-04T20:04:18.948253+00:00
[2021-03-04 22:33:31,263] {standard_task_runner.py:54} INFO - Started process 22 to run task
[2021-03-04 22:33:31,299] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'clean_data', 'clean_data_search_request', '2021-03-04T20:04:18.948253+00:00', '--job_id', '33', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/data_clean.py', '--cfg_path', '/tmp/tmp0bsrhnbr']
[2021-03-04 22:33:31,302] {standard_task_runner.py:78} INFO - Job 33: Subtask clean_data_search_request
[2021-03-04 22:33:31,400] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: clean_data.clean_data_search_request 2021-03-04T20:04:18.948253+00:00 [running]> 6623e80cd770
[2021-03-04 22:33:31,452] {data_clean.py:114} INFO - ***** NOAH starting clean data search_request
[2021-03-04 22:33:31,756] {data_clean.py:122} INFO - ****** NOAH just dropped 1 columns from search_request
[2021-03-04 22:33:31,759] {logging_mixin.py:112} WARNING - /opt/airflow/dags/data_clean.py:130: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ts'][count] = cleaned
[2021-03-04 22:33:31,818] {logging_mixin.py:112} WARNING - /home/airflow/.local/lib/python3.6/site-packages/pandas/core/indexing.py:670: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
[2021-03-04 22:34:18,801] {data_clean.py:132} INFO - ****** NOAH finished cleaning timestamp
[2021-03-04 22:34:18,910] {python_operator.py:114} INFO - Done. Returned value was: None
[2021-03-04 22:34:18,920] {taskinstance.py:1070} INFO - Marking task as SUCCESS.dag_id=clean_data, task_id=clean_data_search_request, execution_date=20210304T200418, start_date=20210304T223331, end_date=20210304T223418
[2021-03-04 22:34:21,351] {local_task_job.py:102} INFO - Task exited with return code 0
