[2021-03-04 22:35:06,248] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: clean_data.merge_data 2021-03-04T20:04:18.948253+00:00 [queued]>
[2021-03-04 22:35:06,288] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: clean_data.merge_data 2021-03-04T20:04:18.948253+00:00 [queued]>
[2021-03-04 22:35:06,288] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2021-03-04 22:35:06,289] {taskinstance.py:881} INFO - Starting attempt 1 of 2
[2021-03-04 22:35:06,290] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2021-03-04 22:35:06,329] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): merge_data> on 2021-03-04T20:04:18.948253+00:00
[2021-03-04 22:35:06,333] {standard_task_runner.py:54} INFO - Started process 36 to run task
[2021-03-04 22:35:06,387] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'clean_data', 'merge_data', '2021-03-04T20:04:18.948253+00:00', '--job_id', '35', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/data_clean.py', '--cfg_path', '/tmp/tmp_8wol0dx']
[2021-03-04 22:35:06,431] {standard_task_runner.py:78} INFO - Job 35: Subtask merge_data
[2021-03-04 22:35:06,548] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: clean_data.merge_data 2021-03-04T20:04:18.948253+00:00 [running]> 6623e80cd770
[2021-03-04 22:35:06,765] {python_operator.py:114} INFO - Done. Returned value was: None
[2021-03-04 22:35:06,777] {taskinstance.py:1070} INFO - Marking task as SUCCESS.dag_id=clean_data, task_id=merge_data, execution_date=20210304T200418, start_date=20210304T223506, end_date=20210304T223506
[2021-03-04 22:35:11,211] {local_task_job.py:102} INFO - Task exited with return code 0
